version: '3.8'

services:
  db:
    image: postgres:16
    container_name: product-postgres
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: shubham
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"

  app:
    image: my-product-service-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://product-postgres:5432/product_db
      SPRING_DATASOURCE_USERNAME: shubham
      SPRING_DATASOURCE_PASSWORD: root

  tempo:
    image: grafana/tempo:latest
    ports:
      - "4317:4317"
      - "4318:4318"
      - "3200:3200"   # if using Tempo query UI
    volumes:
      - ./tempo.yaml:/etc/tempo/tempo.yaml
    command: [ "-config.file=/etc/tempo/tempo.yaml" ]
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"