server:
  port: 8081
spring:
  application:
    name: inventory-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/inventorydb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:root}

management:
  health:
  circuit breakers:
  enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always

  tracing:
    enabled: true
    sampling:
      probability: 1.0   # 100% sampling for local/dev
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
    protocols:
      grpc: http://0.0.0.0:4317
      http: http://0.0.0.0:4318

logging:
  pattern:
    console: >
      %d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36}
      traceId=%X{traceId} spanId=%X{spanId} - %msg%n
#  zipkin:
#    tracing:
#      endpoint: http://localhost:9411/api/v2/spans

#logging:
#  pattern:
#    level: "%5p [${spring.application.name},%X{traceId},%X{spanId}]"




