name: CI for Microservices

on:
  push:
    branches:
      - main
    paths:
      - 'product-service/**'
      - 'inventory-service/**'
      - 'service-registry/**'
      - 'api-gateway/**'
  pull_request:
    branches:
      - main
    paths:
      - 'product-service/**'
      - 'inventory-service/**'
      - 'service-registry/**'
      - 'api-gateway/**'
env:
  RUN_DOCKER_PUSH: "false"    # â¬… set to "true" to run Docker push
  
jobs:
  build-product-service:
    name: Build Product Service
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: mydb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        working-directory: product-service
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/mydb
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: postgres
        run: mvn -B package

      - name: Build & Push Docker
        if: ${{ env.RUN_DOCKER_PUSH == 'true' }}
        uses: mr-smithers-excellent/docker-build-push@v5.3
        with:
          image: shubham7474k/my-ecom-app
          tags: latest, ${{ github.sha }}
          registry: docker.io
          dockerfile: product-service/Dockerfile   # correct
          directory: product-service                # build context
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
